#include "testlib.h"
#include <vector>
#include <string>
#include <algorithm>
using namespace std;

int main(int argc, char* argv[]) {
    registerGen(argc, argv, 1);

    // Choose number of test cases, biased towards small/medium sizes
    int mode = rnd.next(0, 2);
    int P;
    if (mode == 0) P = rnd.next(1, 5);
    else if (mode == 1) P = rnd.next(5, 10);
    else P = rnd.next(10, 20);

    // Helper to generate a single 3x3 board of a given type
    auto genBoard = [&](int type) -> vector<string> {
        vector<string> g(3, string(3, '.'));

        switch (type) {
            case 0: {
                // All white (already initialized)
                break;
            }
            case 1: {
                // All black
                for (int i = 0; i < 3; ++i)
                    for (int j = 0; j < 3; ++j)
                        g[i][j] = '*';
                break;
            }
            case 2: {
                // Single black at random position
                int i = rnd.next(0, 2);
                int j = rnd.next(0, 2);
                g[i][j] = '*';
                break;
            }
            case 3: {
                // Exactly k blacks at random distinct positions
                int k = rnd.next(2, 7);
                vector<int> pos(9);
                for (int i = 0; i < 9; ++i) pos[i] = i;
                shuffle(pos.begin(), pos.end());
                for (int idx = 0; idx < k; ++idx) {
                    int p = pos[idx];
                    int i = p / 3, j = p % 3;
                    g[i][j] = '*';
                }
                break;
            }
            case 4: {
                // Checkerboard pattern, starting with either '*' or '.' at (0,0)
                bool startBlack = rnd.next(0, 1);
                char c0 = startBlack ? '*' : '.';
                char c1 = startBlack ? '.' : '*';
                for (int i = 0; i < 3; ++i)
                    for (int j = 0; j < 3; ++j)
                        g[i][j] = ((i + j) % 2 == 0 ? c0 : c1);
                break;
            }
            case 5: {
                // Plus or border pattern
                if (rnd.next(0, 1) == 0) {
                    // Plus shape
                    g[1][1] = '*';
                    g[0][1] = '*';
                    g[1][0] = '*';
                    g[1][2] = '*';
                    g[2][1] = '*';
                } else {
                    // Border black, center white
                    for (int i = 0; i < 3; ++i)
                        for (int j = 0; j < 3; ++j)
                            g[i][j] = '*';
                    g[1][1] = '.';
                }
                break;
            }
            case 6: {
                // Board generated by random clicks from all-white
                auto toggle = [&](int x, int y) {
                    if (x < 0 || x >= 3 || y < 0 || y >= 3) return;
                    g[x][y] = (g[x][y] == '.') ? '*' : '.';
                };
                int steps = rnd.next(1, 9);
                for (int s = 0; s < steps; ++s) {
                    int i = rnd.next(0, 2);
                    int j = rnd.next(0, 2);
                    toggle(i, j);
                    toggle(i - 1, j);
                    toggle(i + 1, j);
                    toggle(i, j - 1);
                    toggle(i, j + 1);
                }
                break;
            }
            case 7: {
                // Random board with a chosen density
                double probs[3] = {0.25, 0.5, 0.75};
                double p = probs[rnd.next(0, 2)];
                for (int i = 0; i < 3; ++i)
                    for (int j = 0; j < 3; ++j)
                        if (rnd.next() < p)
                            g[i][j] = '*';
                break;
            }
            default:
                break;
        }

        return g;
    };

    vector<vector<string>> boards;

    if (P == 1) {
        // Single test: fully random type
        int t = rnd.next(0, 7);
        boards.push_back(genBoard(t));
    } else {
        // Ensure we have at least all-white and all-black cases
        boards.push_back(genBoard(0)); // all white
        boards.push_back(genBoard(1)); // all black

        while ((int)boards.size() < P) {
            int t = rnd.next(2, 7); // avoid duplicating trivial types too much
            boards.push_back(genBoard(t));
        }

        // Shuffle order of testcases
        shuffle(boards.begin(), boards.end());
    }

    // Output
    println(P);
    for (int idx = 0; idx < P; ++idx) {
        for (int i = 0; i < 3; ++i)
            println(boards[idx][i]);
    }

    return 0;
}
