#include "testlib.h"
#include <vector>
#include <numeric>
#include <algorithm>
#include <set>

using namespace std;

int main(int argc, char* argv[]) {
    registerValidation(argc, argv);

    // Read seven space-separated integers in the range [1, 10^9]
    vector<long long> nums = inf.readLongs(7, 1LL, 1000000000LL, "number");
    inf.readEoln();

    // Sort the input numbers to easily identify s1, s2, s7
    sort(nums.begin(), nums.end());

    long long s1 = nums[0];
    long long s2 = nums[1];
    long long s7 = nums[6];

    // Based on the problem structure (A, B, C, A+B, B+C, C+A, A+B+C)
    // with A <= B <= C and A, B, C > 0, the smallest two numbers must be A and B,
    // and the largest number must be A+B+C.
    // So, A = s1, B = s2, and A+B+C = s7.
    // From A+B+C = s7, we can derive C = s7 - A - B = s7 - s1 - s2.
    long long A = s1;
    long long B = s2;
    long long C = s7 - s1 - s2;

    // Validate properties of the derived A, B, C
    // 1. A, B, C must be positive integers.
    //    A = s1 >= 1 (guaranteed by input range check [1, 10^9])
    //    B = s2 >= 1 (guaranteed by input range check [1, 10^9])
    //    C = s7 - s1 - s2 must be > 0.
    ensuref(C > 0, "Calculated C (%lld) must be positive. s7=%lld, s1=%lld, s2=%lld", C, s7, s1, s2);

    // 2. A <= B <= C must hold.
    //    A <= B (s1 <= s2) is guaranteed by sorting.
    //    B <= C (s2 <= s7 - s1 - s2) must be checked.
    ensuref(B <= C, "Calculated C (%lld) must be >= B (%lld). s7=%lld, s1=%lld, s2=%lld", C, B, s7, s1, s2);

    // 3. The sums A+B, B+C, C+A, A+B+C must be among the given numbers and within [1, 10^9].
    //    A+B+C = s7, which is in [1, 10^9] by input range check.
    //    B+C = s7 - s1. Since s7 <= 10^9 and s1 >= 1, s7-s1 <= 10^9-1. B+C = s2+C >= 1+1=2. Range [2, 10^9-1] is fine.
    //    C+A = s7 - s2. Since s7 <= 10^9 and s2 >= 1, s7-s2 <= 10^9-1. C+A = C+s1 >= 1+1=2. Range [2, 10^9-1] is fine.
    //    A+B = s1 + s2. Since s1 >= 1, s2 >= 1, s1+s2 >= 2. We must check s1+s2 <= 10^9.
    ensuref(A + B <= 1000000000LL, "Calculated A+B (%lld) exceeds 10^9. s1=%lld, s2=%lld", A + B, s1, s2);

    // Construct the expected multiset of seven numbers using the derived A, B, C
    vector<long long> expected_nums;
    expected_nums.push_back(A);
    expected_nums.push_back(B);
    expected_nums.push_back(C);
    expected_nums.push_back(A + B);
    expected_nums.push_back(B + C);
    expected_nums.push_back(C + A);
    expected_nums.push_back(A + B + C);

    // Sort the expected multiset
    sort(expected_nums.begin(), expected_nums.end());

    // Compare the sorted input multiset with the sorted expected multiset
    // If they are identical, the input is valid according to the problem structure.
    ensuref(nums == expected_nums, "Input numbers do not match the expected set generated by A, B, C");

    // Ensure no extra input
    inf.readEof();

    return 0;
}
